### ISSUE TITLE
image_strip.py crashes when a file is in the middle of uploading to /srv/ObjectDB/unprocessed

### ISSUE THREAD

**Issue by mcanul** [UHMC/landmark-analysis#4]
`Processing file: 2086945223_53a0081c33_b.jpg`
`2017-08-25 14:34:18.619266: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.`
`2017-08-25 14:34:18.619302: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.`
`2017-08-25 14:34:18.619311: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.`
`2017-08-25 14:34:18.619318: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.`
`2017-08-25 14:34:18.619325: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.`
`Traceback (most recent call last):`
 ` File "image_strip.py", line 47, in <module>`
   `odapi_output = pickle.dumps(odapi_adapter.get_objects(f.name))  # Pickle odapi_output`
  `File "/home/uhmcabit/object-analysis/odapi_adapter.py", line 73, in get_objects`
    `image_np = load_image_into_numpy_array(image)`
  `File "/home/uhmcabit/object-analysis/odapi_adapter.py", line 62, in load_image_into_numpy_array`
`    return np.array(image.getdata()).reshape(`
`  File "/home/uhmcabit/object-analysis/local/lib/python2.7/site-packages/PIL/Image.py", line 1187, in getdata`
    `self.load()`
  `File "/home/uhmcabit/object-analysis/local/lib/python2.7/site-packages/PIL/ImageFile.py", line 231, in load`
    `"(%d bytes not processed)" % len(b))`
`IOError: image file is truncated (27 bytes not processed)`

**Comment by knight7** [comment]
Sounds like a job for a next_available_image() function.

**Comment by knight7** [comment]
I think ideally, we buffer this by skipping unreadable image files and adding them to a queue to be processed with lower effective priority than the current set of readables. (Dynamically usurps the current 3-second wait, perhaps?)

I guess for the sake of development time, it'd just be faster to implement an idle before attempting again, or perhaps even skipping the image entirely. This option would of course only be a temporary fix.
